- name: Installing command line tools
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - htop
    - vim
    - tmux
    - elinks
    - graphviz
    - ack
    - strace
- name: Installing python command line tools
  pip:
    name: "{{ item }}"
    state: latest
  loop:
    - s-tui
